services:
  app:
    build: .
    container_name: authProject
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
      - PORT=${PORT}
    command: npm run dev
    ports:
      - "${PORT}:${PORT}" # host:container
    depends_on:
      - db
      - cache
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: authProject-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - authProject-postgres-data:/var/lib/postgresql/data

  cache:                     
    image: redis:7-alpine
    container_name: authProject-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  authProject-postgres-data:
  redis-data: